// Generated by Xata Codegen 0.25.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "scoreboard",
    columns: [
      { name: "score", type: "int", notNull: true, defaultValue: "0" },
      {
        name: "character",
        type: "string",
        notNull: true,
        defaultValue: "soldier",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Scoreboard = InferredTypes["scoreboard"];
export type ScoreboardRecord = Scoreboard & XataRecord;

export type DatabaseSchema = {
  scoreboard: ScoreboardRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Katr-Games-s-workspace-rrfe4h.us-east-1.xata.sh/db/katrscoreboard",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
